name: om
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py311hca03da5_1
  - aiohappyeyeballs=2.6.1=py311hca03da5_0
  - aiohttp=3.13.2=py311haa24f5a_0
  - aiosignal=1.4.0=py311hca03da5_0
  - appnope=0.1.4=py311hca03da5_0
  - arrow-cpp=21.0.0=hd376218_0
  - asttokens=3.0.0=py311hca03da5_0
  - attrs=25.4.0=py311hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotlicffi=1.1.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - comm=0.2.3=py311hca03da5_0
  - datasets=3.3.2=py311hca03da5_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=py311hca03da5_0
  - dill=0.3.8=py311hca03da5_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.20.0=py311hca03da5_0
  - frozenlist=1.8.0=py311h50f4ffc_0
  - fsspec=2024.12.0=py311hca03da5_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - hf-xet=1.1.8=py311h8cd5084_0
  - huggingface_hub=0.34.4=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py311hca03da5_0
  - ipykernel=6.31.0=py311h7eb115d_0
  - ipython=9.7.0=py311hca03da5_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - jedi=0.19.2=py311hca03da5_0
  - jupyter_client=8.6.3=py311hca03da5_1
  - jupyter_core=5.8.1=py311hca03da5_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.15.0=h538a5d9_4
  - libunistring=1.3=h1799b2a_0
  - libuv=1.48.0=h80987f9_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib-inline=0.2.1=py311hca03da5_0
  - multidict=6.7.0=py311h254cc4a_0
  - multiprocess=0.70.15=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - numexpr=2.14.1=py311h5fbe615_0
  - openssl=3.0.18=h9b4081a_0
  - orc=2.2.0=hec253e6_0
  - packaging=25.0=py311hca03da5_1
  - pandas=2.3.3=py311h3f644e9_1
  - parso=0.8.5=py311hca03da5_0
  - pexpect=4.9.0=py311hca03da5_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=py311hca03da5_0
  - prompt-toolkit=3.0.52=py311hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py311h80987f9_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py311hca03da5_0
  - pyarrow=21.0.0=py311hc6ded6b_0
  - pycares=4.10.0=py311h091efcb_0
  - pycparser=2.23=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h80987f9_0
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.2=py311h80987f9_0
  - pyzmq=27.1.0=py311h5a8c52c_1
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - regex=2025.9.1=py311h254cc4a_0
  - requests=2.32.5=py311hca03da5_1
  - safetensors=0.6.2=py311h931abed_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - tqdm=4.67.1=py311h7eb115d_1
  - traitlets=5.14.3=py311hca03da5_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - uvloop=0.22.1=py311h8e34c70_1
  - wcwidth=0.2.13=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.22.0=py311haa24f5a_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - click==8.3.0
      - dnspython==2.8.0
      - email-validator==2.3.0
      - fastapi==0.121.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - jinja2==3.1.6
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.5
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pillow==12.0.0
      - protobuf==4.25.8
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - sentry-sdk==2.44.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - sympy==1.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - termcolor==3.2.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - transformers==4.57.1
      - typer==0.20.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - vadersentiment==3.3.2
      - watchfiles==1.1.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
prefix: /Users/yuchen80/miniconda3/envs/om
